name: CI

on:
  - pull_request
  - push

jobs:
  tests:
    name: Tests

    runs-on: ubuntu-latest

    environment: Staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: xdebug

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress

      - run: echo "${{ secrets.LARAVEL_ENV_TEST }}" >> ./.env.testing
      - run: php artisan cache:clear
      - run: php artisan config:clear
      - run: php artisan route:clear
      - run: php artisan migrate --no-interaction --env=testing
      - run: php artisan migrate:refresh --no-interaction --env=testing
      - run: php artisan db:seed --no-interaction --env=testing

      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Fix code coverage paths
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}