
name: My Actions
on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]
jobs:
  build:
    name: Build and deploy to web server
    runs-on: self-hosted
    environment: Prod
    steps:
      - uses: actions/checkout@v3
      - run: php --version
      - run: composer --version
      - run: composer install
      - run: composer update
      - run: echo "${{ secrets.LARAVEL_ENV_TEST }}" >> ./.env.testing
      - run: php artisan cache:clear
      - run: php artisan config:clear
      - run: php artisan route:clear
      - run: php artisan migrate --no-interaction --env=testing
      - run: php artisan migrate:refresh --no-interaction --env=testing
      - run: php artisan db:seed --no-interaction --env=testing
      - run: php artisan test --env=testing
      - run: echo "${{ secrets.LARAVEL_ENV }}" >> ./.env
      - run: php artisan cache:clear
      - run: php artisan config:clear
      - run: php artisan route:clear
      - run: cat ./.env
      - run: rm -rf ./vendor
      - run: rsync -avz -e 'ssh' ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ${{ secrets.DEPLOY_PATH }}
            composer install
            composer update
            php artisan migrate
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
